### ISSUE TITLE
Serverless SignalR

### ISSUE THREAD

**Issue by Durkee** [jamiewest/signalr_core#10]
First, thank you for the dart code.
 
Questions:
Will this work with "Serverless" Azure (i.e. without a hub)? This link talks about the different modes: 
https://github.com/Azure/azure-signalr/blob/dev/docs/faq.md#service-mode

I noticed we were lacking a sample project.  I need to know how to send my UserId and Target so i get only my messages.  https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-output?tabs=csharp

**Comment by jamiewest** [comment]
This should work with the `Azure SignalR Service` but I have not had a chance to test it. The reason I say it should work is that it is a very close replica of the [typescript client](https://github.com/dotnet/aspnetcore/tree/master/src/SignalR/clients/ts/signalr/src). I very much want to test and confirm this use case but I am currently waiting on [PR](https://github.com/dart-lang/http/pull/388) to be published before focusing on anything else.

Regarding the `UserId` and `Target`, these are arguments on a method that would be setup in the `Hub`. This library would `invoke` that method by passing the `UserId` and `Target`. The old SignalR would allow a proxy to the `Hub` on the connection object, but this isn't in the new version of SignalR.

**Comment by Durkee** [comment]
@jamiewest  Thank you for the reply.  When I get time I will try it out with Azure SignalR (Serverless)
