### ISSUE TITLE
proxy none

### ISSUE THREAD

**Issue by yenge35** [jamiewest/signalr_core#2]
merhaba;

> String serverUrl = "http://uygulama.cari24.com";
        mHubConnection = new HubConnection(serverUrl);

        mHubProxy = mHubConnection.createHubProxy("myhub");

createHubProxy sizde çalışmıyor

**Comment by jamiewest** [comment]
Not enough information, is this a request or issue?

**Comment by yenge35** [comment]
http://uygulama.cari24.com/myhub bu çalışmıyor
 mHubProxy = mHubConnection.createHubProxy("myhub") Android Studio da böyle iken çalışıyor
ben  hub adını nereye yazacağım.

**Comment by yenge35** [comment]
` final connection = HubConnectionBuilder()
        .withUrl("http://uygulama.cari24.com/myhub")
        .build();

    await connection.start();`
bu çalışmıyor

**Comment by yenge35** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/7754186/71665381-c0598980-2d6d-11ea-812e-df4cada8e73d.PNG)
bu benim kodum maalesef çalışmıyor

**Comment by jamiewest** [comment]
I sorry, I am not able to understand your request. I believe the `createHubProxy` method is in the older SignalR library and not the newer Core one. If you need additional control over the connection, i.e. using proxies, you might try using a custom `HttpClient` that can be specified in the `HubConnectionBuilder`.
