### ISSUE TITLE
Azure Signalr

### ISSUE THREAD

**Issue by JohnnyOpcode** [jamiewest/signalr_core#24]
I'm a bit (pun) unclear of the URL form when making a Flutter Client connection to an Azure Signalr Hub.

Examples are far and few to come by on the internet and everything I try returns a 404 or 400 error.

Has this been tested with Azure?

Johnny

**Comment by laimonas** [comment]
I can confirm that it is working. I have my test project. Some code samples.
final connection = HubConnectionBuilder()
      .withUrl(
	  // web
          'http://localhost:5000/scrum-poker',
	  // Android emulator
          // 'https://10.0.2.2:5000/scrum-poker',
	  // Azure
          //'https://xxxxx.azurewebsites.net/scrum-poker',
          HttpConnectionOptions(
            client: IOClient(HttpClient()..badCertificateCallback = (x, y, z) => true),
            transport: HttpTransportType.webSockets,
            logging: (level, message) => print(message),
          ))
      .withAutomaticReconnect()
      .build();

// NET.Core
public void ConfigureServices(IServiceCollection services)
        {
            services.AddSignalR(o => o.EnableDetailedErrors = true);
            services.AddCors(options => options.AddPolicy("AllowAll", builder =>
            {
                builder
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowAnyOrigin();
            }));

            services.AddSignalR(o => o.EnableDetailedErrors = true);
        }

**Comment by JohnnyOpcode** [comment]
Excellent. That filled in the missing bits (pun again).

Thank-you
