### ISSUE TITLE
[Question] Is the code a port of the AspNetCore 3.1 Typescript client codebase?

### ISSUE THREAD

**Issue by markphillips100** [jamiewest/signalr_core#25]
Before delving into the repo's code for a deeper understanding, if possible, could you tell me how close this codebase is to the official AspNetCore 3.1 Typescript client?  Are there missing APIs or behaviours for example?

My reason for asking is back in March I created a [fork](https://github.com/markphillips100/signalr_client/tree/dev) of another published package (called signalr_client) to support code parity with the 3.1 TS client - this was primarily to have the auto-reconnect feature.  I had no response from the package's author in regards to a PR so have been pursuing a possible PR with another developer who has also forked that original package and published their own name (signalr_netcore).

My preference is to use what's already available and if your package already has code parity with the Typescript client I'd be tempted to use yours.  I don't want to add to the oversupply of packages if it can be helped.

**Comment by jamiewest** [comment]
I believe when I did the port that it was against the 3.1 codebase and I tried to match as closely as possible. I would have to go back and do a comparison however to find where there are any differences. This library does contain the reconnect feature that should match the official docs and is also is compatible with web. My plan is to bring parity up to 5.0 and write more tests. I work on this part-time and hope to improve this to be a first class SignalR client for Dart.

**Comment by markphillips100** [comment]
Thanks for the response @jamiewest.  Just an FYI, my 3.1 TS port PR coincidentally just got approved and merged into the signalr_netcore package (0.1.8), so now there are 2 packages on pub.dev that are typescript compliant. I'm not sure this benefits the community but I guess better 2 than none :-)

I too had plans to align with .NET 5's TS client but would happily switch to another package like yours if it had code parity.  Any ETA on when you might get around to this?  I understand working part-time so no pressure.

As for unit tests, it's great that you are doing those.  The original package I use had none and instead had test/sample apps.  Nice from an integration perspective but the repo would benefit from unit tests, at least in compliance with what the typescript has already.

**Comment by jamiewest** [comment]
I would like to bring it to parity with 5.0 by the end of the year time permitting. I will take a look at `signalr_netcore`, if there is a better library out there for this then I may just concentrate my efforts contributing there. At the time there weren't too many feature complete web compatible alternatives.
