### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by Chris1234567899** [jamiewest/signalr_core#32]
I think some more details on how to use this package would be highly appreciated.

**Comment by ghulamostafa** [comment]
For integrating it with a .NET application, here you go
https://ghulamustafa.com/2021/01/16/how-to-use-signalr-with-flutter-for-chat/

**Comment by jamiewest** [comment]
I agree, I'd like to go through the code and improve the comments to include examples and then have docs generate when we merge.  If anyone can make a PR with doc additions it would be greatly appreciated. Thanks @ghulamostafa for sharing!
