### ISSUE TITLE
Does not work with load balancer and sticky sessions setup

### ISSUE THREAD

**Issue by juanrequeijo** [jamiewest/signalr_core#40]
When I configure my backend to work like:

https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html

signalr_core crash:

![image](https://user-images.githubusercontent.com/19295630/107409806-4dcbe900-6aeb-11eb-95e5-ce02b30c0f55.png)

**Comment by jamiewest** [comment]
Would you be able to test connecting to your backend via the javascript client and post back the results?

**Comment by juanrequeijo** [comment]
Yes, in javascript it works as expected.

![image](https://user-images.githubusercontent.com/19295630/107514315-44448e80-6b88-11eb-9d85-34bdda5aaca6.png)

**Comment by juanrequeijo** [comment]
You should add header cookie  in custom http client
![image](https://user-images.githubusercontent.com/19295630/133438968-76e79e09-cb33-48c5-a340-a4303d1d718f.png)
