### ISSUE TITLE
reConnection again and again

### ISSUE THREAD

**Issue by SamiraAriaeifar** [jamiewest/signalr_core#55]
I used your package in my app.
 It is constantly trying to reconnect
I do not want it 
I want to try to reconnect when the internet connection is disconnected or Hub Connection stopped..
How do I fix it?
![Untitled](https://user-images.githubusercontent.com/59957217/117921495-0df0e980-b306-11eb-87fc-8d8e1f622da3.png)

**Comment by SamiraAriaeifar** [comment]
PLZ ,HELP TO FIX IT ,THANKS

**Comment by eli1stark** [comment]
How do you reconnect?

**Comment by birimkulov951** [comment]
How to reconnect properly?

**Comment by andredealmei** [comment]
> How to reconnect properly?

 You call withAutomaticReconnect, passing a list of int (time in millesec) or a implementation of RetryPolicy
`final list = [500,1000,2000,3000]`
`HubConnectionBuilder() .withUrl().withAutomaticReconnect(list)`
