### ISSUE TITLE
Client-to-server streaming

### ISSUE THREAD

**Issue by ashyr-tm** [jamiewest/signalr_core#56]
Hi guys.
I want to use stream over a socket, and I found how to receive via the stream using the connection.stream() method, but I could not find how to send via the stream. 

I need a method similar to the one used in Javascript.

`const subject = new signalR.Subject();
yield connection.send("UploadStream", subject);`
[https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-5.0#javascript-client](url)

I will be glad for your help

**Comment by bretbas** [comment]
I also want to know how to do it
