### ISSUE TITLE
Unit Testing Hub

### ISSUE THREAD

**Issue by milodude** [jamiewest/signalr_core#66]
I'm facing an issue while trying to unit test my hub. I just need be able to go through the initialization of the widget without trying to make an actual http connection. The issue with provided implementation comes when going through this line

`var hubConnection = HubConnectionBuilder().withUrl(hubDivisionConnectionString).build();`

build() method returns a HubConnection but this is an abstract class which can not be mocked. Can someone give me a hint on how can I be able to test this?

**Comment by jamiewest** [comment]
We might need a `MockHubConnection` like the [http](https://pub.dev/packages/http) package has. Anyone up for making a PR?

**Comment by milodude** [comment]
Thanks for posting a reply I'm just quite busy and completely forgot about this issue I raised. I came up with a workaround a few days ago. I had to implement a kind of startup to pass each of the services to my pages each time they are called(like a DI in c#). By doing this I was able to mock the hubBuilder since I mocked the service and then pass this while initializing the page in my test.

`void main() {
  final mockObserver = MockNavigatorObserver();
  final countryService = MockCountryService();
  final divisionService = MockDivisionService();
  final hubBuilder = MockHubBuilder();
  **final hc = MockHubConnection();**
  final reportService = MockReportService();

  **Widget widgetSetupToBeTested({Widget child}) {
    when(hc.start()).thenAnswer((realInvocation) => Future.value());
    when(hc.stop()).thenAnswer((realInvocation) => Future.value());
    when(hc.onclose((exception) { })).thenAnswer((realInvocation) => Future.value());
    when(hc.on(any, (arguments) { })).thenAnswer((realInvocation) => Future.value());

    when(hubBuilder.hubConnection).thenAnswer((_)=>hc);
    return MaterialApp(
      home: child,
      navigatorObservers: [mockObserver],
    );
  }**

  testWidgets(
      'Given a back button in the menu When clicking on back icon button should call navigator pop',
      (tester) async {
    // ARRANGE
    var countryList = <CountryDto>[];
    countryList.add(CountryDto(id: 'dcfes-8erdx-45ssc-ssx', nombre: 'Argentina'));

    var divisionList = <DivisionDto>[];
    divisionList.add(DivisionDto(countryId: 70,supportName: 'Test', divisionName: 'Test', supportId: 1, divisionId: 1, providerId: 1, divisionStatus: 'InProgress', start: null, type: 'Document',
        tier: 'Tier1',
        summary: SummaryDto(totalPages: 7, uploadedPages: 7)));

    var errorSummary = ErrorSummaryDto(totalDivisions: 10, totalError: 5, totalSucceed: 5);
    when(reportService.getErrorsSummary()).thenAnswer((realInvocation) => Future.value(errorSummary));
    
    when(countryService.getCountries()).thenAnswer((_) async => Future.value(countryList));
    when(divisionService.getDivisions(any)).thenAnswer((_) async => Future.value(divisionList));
    
    **await tester.pumpWidget(
        widgetSetupToBeTested(child: CrudoPage(countryService: countryService,hubBuilder: hubBuilder, reportService: reportService)));**
    await tester.pump();

    //ACT
    final backButton = find.byIcon(Icons.arrow_back);
    await tester.tap(backButton);
    await tester.pump();
    
    //ASSERT
    verify(mockObserver.didPop(any, any));
  });`

I bold the main lines. The widgetSetupToBeTested method is called in each and every test in order to emulate a kind of "Setup" method each time a test runs. Inside of it I mocked the HubBuilder and the HubConnection necessary  methods by mocking them with mockito like this(you can disregard the remaining services I had to mock) 

`class MockHubBuilder extends Mock implements HubBuilder {}
class MockHubConnection extends Mock implements HubConnection {}` 

And that is it. I know it might look like a difficult approach but that is the only workaround I was able to find since test at my work are a must. Any suggestions or insights would be appreaciated and if this satisfies my requirement feel free to close the ticket.

**Comment by jamiewest** [comment]
Thanks for the feedback, I kinda want to leave this open so I can track adding better testing support. I haven't had time to work on this lib much and a lot of my time has been spent porting the Microsoft.Extensions namespace to dart recently. I'm hoping I can return to this soon.
