### ISSUE TITLE
missing methods for lifecycle events

### ISSUE THREAD

**Issue by shovelmn12** [jamiewest/signalr_core#7]
I am trying to know when my client disconnected or connected.
I would recommend adding onOpen/onStart/onConnected callback.

The best thing would be to do something like:
```
class HubConnection ... {
   final _state =  BehaviourSubjscet<HubConnectionState>. seeded(HubConnectionState.disconnected);

   HubConnectionState get state => _state.value

   Stream get onConnected => _state.where(s => s == HubConnectionState.connected);
   Stream get onDisconnected => _state.where(s => s == HubConnectionState.disconnected);
   Stream get onConnecting => _state.where(s => s == HubConnectionState.connecting);
   ...
}
```

all you need to do now is to change all assignments of state to _state.add(HubConnectionState.whateverState) and when using the client now i can get all the info i need for lifecycle events.

**Comment by jamiewest** [comment]
There are `onclose`, `onreconnecting`, and `onreconnected` callbacks on the client. I do not have connect related callbacks because the ASP.NET clients do not have those. Is there a specific use case where this is needed?

**Comment by shovelmn12** [comment]
https://github.com/jamiewest/signalr_core/issues/6#issuecomment-605603830

explanation
