### ISSUE TITLE
The plugin is not accepting https connections

### ISSUE THREAD

**Issue by Katekko** [jamiewest/signalr_core#8]
I need a way to set certificate false when I are in localhost. Otherwise thats the error that I get :(

![image](https://user-images.githubusercontent.com/13632735/77811244-e0040380-7077-11ea-85c3-dc4320db8012.png)

**Comment by jamiewest** [comment]
Set the `client` in `HttpConnectionOptions`  like so:

```dart
HttpConnectionOptions(
   client: IOClient(HttpClient()..badCertificateCallback = (x, y, z) => true)
)
```
This will force the client to accept whatever cert is being used. If you need to use a specific cert, you can set the `SecurityContext` within the `HttpClient`.
