### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by jamiewest** [jamiewest/signalr_core#96]
Hi everyone, 

I'd like to give a brief update regarding the future of this repository. I am currently working on a replacement `signalr` package that will provide better testability, nicer looking code, and a server implementation written in dart. I hope to have a working release in the coming months. The new package home will be `package:signalr/signalr.dart`.

**Comment by zuboje** [comment]
Out of curiosity, is there any ETA, or any assistance needed? I used this plugin for some time and I would be more than happy to help if I can in any capacity.

**Comment by jamiewest** [comment]
Sure, check out the [repo](https://github.com/jamiewest/signalr), it is mostly just porting code [aspnetcore/signalr](https://github.com/dotnet/aspnetcore/tree/main/src/SignalR).

**Comment by definev** [comment]
Is it ready yet?

**Comment by misici234** [comment]
@jamiewest I don't understand how we can use the new package in our Flutter projects.

**Comment by ugumerie** [comment]
Thank you for your wonderful contribution. Any update on this yet?

**Comment by andredealmei** [comment]
do you need any help with the new one ? i can contribute if you show any path to follow

**Comment by aeb-dev** [comment]
I implemented a new client from scratch you can check it here: https://github.com/aeb-dev/signalr_dart

**Comment by jamiewest** [comment]
Hi all, sorry for the neglect of this repo. I went through and did a few updates, my plan is to get this matching the typescript client library authored by Microsoft. My intent is to keep this library as close as possible to that library in terms of the features and api. However dart language features and style will be utilized where appropriate. 

I would still like to port the c# equivalent of the library but that requires my extensions library be up to date as well. I'm still spending a lot of time in that area trying to match the latest .net changes.

I look forward to actually using this library in a project for myself, thanks for everyone that has stuck around and offered help in the comments.
